# Generated by Django 3.0.6 on 2021-05-07 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='date_birth',
            new_name='birth_date',
        ),
    ]
