# Generated by Django 3.0.6 on 2021-06-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='opinions',
        ),
        migrations.AddField(
            model_name='client',
            name='money',
            field=models.IntegerField(default=0),
        ),
    ]
