# Generated by Django 3.0.6 on 2020-05-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hola',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
