# Generated by Django 3.0.6 on 2020-05-17 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_hola'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='hola',
        ),
    ]
