# Generated by Django 3.0.6 on 2021-06-10 13:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_desc', models.CharField(default='', max_length=500)),
                ('long_desc', models.CharField(default='', max_length=10000)),
                ('image', models.ImageField(upload_to='game_pics')),
                ('banner_img', models.ImageField(upload_to='game_pics')),
                ('stock', models.IntegerField(default=0)),
                ('release_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('new_game', models.BooleanField(default=True)),
                ('lowest_price', models.IntegerField(blank=True, null=True)),
                ('languages', models.CharField(default='ES', max_length=200)),
                ('system_requirements', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key_value', models.CharField(max_length=17)),
                ('price', models.IntegerField(null=True)),
                ('region', models.CharField(choices=[('1', 'EU'), ('2', 'RU')], max_length=50)),
                ('used', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-price'],
            },
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinion', models.CharField(max_length=1000)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Shopping_cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
