# Generated by Django 3.0.6 on 2021-05-07 07:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=500)),
                ('image', models.ImageField(default='default.jpg', upload_to='article_pics')),
                ('stock', models.IntegerField(default=0)),
                ('release_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('new_article', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key_value', models.CharField(max_length=17)),
                ('price', models.IntegerField()),
                ('region', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shopping_cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('articles', models.ManyToManyField(to='appsite.Article')),
            ],
        ),
    ]
