# Generated by Django 3.0.6 on 2021-06-10 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appsite', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping_cart',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Client'),
        ),
        migrations.AddField(
            model_name='shopping_cart',
            name='keys',
            field=models.ManyToManyField(to='appsite.Key'),
        ),
        migrations.AddField(
            model_name='opinion',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Client'),
        ),
        migrations.AddField(
            model_name='opinion',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsite.Game'),
        ),
        migrations.AddField(
            model_name='key',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsite.Game'),
        ),
        migrations.AddField(
            model_name='key',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.Client'),
        ),
        migrations.AddField(
            model_name='key',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Seller'),
        ),
    ]
