# Generated by Django 3.0.6 on 2021-05-07 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appsite', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping_cart',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Client'),
        ),
        migrations.AddField(
            model_name='key',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsite.Article'),
        ),
    ]
