# Generated by Django 3.0.6 on 2020-05-18 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0002_auto_20200518_0220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsite.Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsite.Client')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='opinions',
            field=models.ManyToManyField(through='appsite.Opinion', to='appsite.Article'),
        ),
    ]
