# Generated by Django 3.0.6 on 2021-06-10 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('appsite', '0003_auto_20210610_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Client'),
        ),
    ]
