# Generated by Django 3.0.6 on 2020-05-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0004_auto_20200520_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='desc',
            field=models.CharField(max_length=500),
        ),
    ]
