# Generated by Django 3.0.6 on 2021-06-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210611_1530'),
        ('appsite', '0004_auto_20210610_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='key_value',
            field=models.CharField(max_length=17, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='opinion',
            unique_together={('client', 'game')},
        ),
    ]
