# Generated by Django 3.0.6 on 2021-06-15 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210611_1530'),
        ('appsite', '0005_auto_20210615_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.Client'),
        ),
    ]
