# Generated by Django 3.0.6 on 2021-06-21 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0007_auto_20210621_1344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opinion',
            options={'ordering': ['-date_posted']},
        ),
    ]
