# Generated by Django 3.0.6 on 2021-06-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='genre',
            field=models.CharField(choices=[('1', 'Sandbox'), ('2', 'RTS'), ('3', 'FPS'), ('4', 'MOBA'), ('5', 'RPG'), ('6', 'Simulation and sports'), ('7', 'Puzzlers and party games'), ('8', 'Action adventure'), ('9', 'IRL'), ('10', 'Other')], default='a', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='img_prepost',
            field=models.ImageField(default='default.jpg', upload_to='blog_pics'),
        ),
    ]
