# Generated by Django 3.0.6 on 2021-06-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210610_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='teaser_content',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
