# Generated by Django 3.0.6 on 2021-06-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210621_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='genre',
            field=models.CharField(choices=[('Guides', 'Guides'), ('News', 'News'), ('IRL', 'IRL'), ('Games', 'Games'), ('Other', 'Other')], default='a', max_length=50),
        ),
    ]
